// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Mirrors `CheckoutStatus` in the native cores.
enum NativeCheckoutStatus {
  succeeded,
  failed,
  cancelled,
  pending,
  expired,
}

/// `standard` (not `default` — a reserved Dart keyword) is the system "X"
/// icon on Android; `back` is a back-arrow icon the SDK draws itself. No
/// iOS equivalent — see [NativeDismissButtonStyle] for iOS's dismiss button.
enum NativeCloseButtonStyle {
  standard,
  back,
}

enum NativeCloseButtonPosition {
  start,
  end,
}

/// Mirrors `SFSafariViewController.DismissButtonStyle`. No Android
/// equivalent — see [NativeCloseButtonStyle] for Android's close button.
enum NativeDismissButtonStyle {
  done,
  close,
  cancel,
}

/// Mirrors `UIViewController.modalPresentationStyle` as used to present the
/// checkout sheet. No Android equivalent — Custom Tabs has no comparable
/// page-sheet-vs-full-screen distinction in this SDK.
enum NativePresentationStyle {
  pageSheet,
  fullScreen,
}

/// Forces the browser's light/dark appearance regardless of the system
/// setting. Exists independently on `android` and `ios` (not shared) even
/// though the values are identical, matching every other field here.
enum NativeBrowserColorScheme {
  system,
  light,
  dark,
}

/// Mirrors `CheckoutEvent` in the native cores. Lifecycle-only — never used
/// to decide the checkout outcome.
enum NativeEventType {
  opened,
  returnReceived,
  closed,
}

class StartRequest {
  StartRequest({
    required this.checkoutUrl,
    required this.returnUrl,
    this.customization,
  });

  /// Absolute session URL from the merchant backend.
  String checkoutUrl;

  /// Absolute URL the native SDK watches for. Its scheme must be registered
  /// as a URL type in Info.plist (iOS) / an intent-filter on the redirect
  /// activity (Android), so the OS routes the checkout return back to this
  /// app.
  String returnUrl;

  /// Appearance customization for the checkout browser.
  NativeBrowserCustomization? customization;

  List<Object?> _toList() {
    return <Object?>[
      checkoutUrl,
      returnUrl,
      customization,
    ];
  }

  Object encode() {
    return _toList();  }

  static StartRequest decode(Object result) {
    result as List<Object?>;
    return StartRequest(
      checkoutUrl: result[0]! as String,
      returnUrl: result[1]! as String,
      customization: result[2] as NativeBrowserCustomization?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StartRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(checkoutUrl, other.checkoutUrl) && _deepEquals(returnUrl, other.returnUrl) && _deepEquals(customization, other.customization);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'StartRequest(checkoutUrl: $checkoutUrl, returnUrl: $returnUrl, customization: $customization)';
  }
}

/// Mirrors the native `BrowserCustomization`. `android`/`ios` carry options
/// that only exist on that one platform — native only ever reads its own
/// bag, so this crosses both platforms from one Dart type without either
/// side seeing the other's fields.
///
/// No shared/top-level fields: `toolbarColor` was originally shared, but
/// iOS's equivalent (`preferredBarTintColor`) is deprecated as of iOS 26
/// with no replacement and confirmed to have no visible effect there — not
/// worth a color knob that's already inert on the majority of iOS devices.
/// Same reasoning killed iOS's `controlTintColor` outright (it rested on
/// the identically-deprecated `preferredControlTintColor`).
class NativeBrowserCustomization {
  NativeBrowserCustomization({
    this.android,
    this.ios,
  });

  NativeAndroidBrowserOptions? android;

  NativeIosBrowserOptions? ios;

  List<Object?> _toList() {
    return <Object?>[
      android,
      ios,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeBrowserCustomization decode(Object result) {
    result as List<Object?>;
    return NativeBrowserCustomization(
      android: result[0] as NativeAndroidBrowserOptions?,
      ios: result[1] as NativeIosBrowserOptions?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeBrowserCustomization || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(android, other.android) && _deepEquals(ios, other.ios);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeBrowserCustomization(android: $android, ios: $ios)';
  }
}

/// Every field is `null` by default. `null` isn't resolved to a fallback
/// anywhere in Dart — it crosses the channel as-is, and the native side
/// decides what "unset" means (usually: don't call the corresponding
/// `CustomTabsIntent.Builder` setter at all, so the Custom Tab host's own
/// live default applies). This is deliberate: hardcoding a guess at "the
/// platform default" in Dart can go stale the moment the host changes it,
/// silently changing behavior for every integrator who never touched that
/// field.
///
/// Pigeon encodes this class as a fixed-position list, not a keyed map —
/// `decode()` reads `result[0]`, `result[1]`, ... by index, matching
/// declaration order exactly. Future fields must be appended at the end,
/// never inserted, or every field after the insertion point silently reads
/// the wrong value. Regenerate all three codegen targets together after any
/// change (`dart run pigeon --input pigeons/messages.dart`).
class NativeAndroidBrowserOptions {
  NativeAndroidBrowserOptions({
    this.toolbarColor,
    this.closeButtonStyle,
    this.closeButtonPosition,
    this.shareButtonEnabled,
    this.showTitleEnabled,
    this.urlBarHidingEnabled,
    this.bookmarksButtonEnabled,
    this.downloadsButtonEnabled,
    this.navigationBarColor,
    this.navigationBarDividerColor,
    this.colorScheme,
  });

  /// ARGB, i.e. `Color.toARGB32()`.
  int? toolbarColor;

  NativeCloseButtonStyle? closeButtonStyle;

  NativeCloseButtonPosition? closeButtonPosition;

  /// Hides the toolbar's share icon when `false`.
  bool? shareButtonEnabled;

  bool? showTitleEnabled;

  bool? urlBarHidingEnabled;

  bool? bookmarksButtonEnabled;

  bool? downloadsButtonEnabled;

  int? navigationBarColor;

  int? navigationBarDividerColor;

  NativeBrowserColorScheme? colorScheme;

  List<Object?> _toList() {
    return <Object?>[
      toolbarColor,
      closeButtonStyle,
      closeButtonPosition,
      shareButtonEnabled,
      showTitleEnabled,
      urlBarHidingEnabled,
      bookmarksButtonEnabled,
      downloadsButtonEnabled,
      navigationBarColor,
      navigationBarDividerColor,
      colorScheme,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeAndroidBrowserOptions decode(Object result) {
    result as List<Object?>;
    return NativeAndroidBrowserOptions(
      toolbarColor: result[0] as int?,
      closeButtonStyle: result[1] as NativeCloseButtonStyle?,
      closeButtonPosition: result[2] as NativeCloseButtonPosition?,
      shareButtonEnabled: result[3] as bool?,
      showTitleEnabled: result[4] as bool?,
      urlBarHidingEnabled: result[5] as bool?,
      bookmarksButtonEnabled: result[6] as bool?,
      downloadsButtonEnabled: result[7] as bool?,
      navigationBarColor: result[8] as int?,
      navigationBarDividerColor: result[9] as int?,
      colorScheme: result[10] as NativeBrowserColorScheme?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAndroidBrowserOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(toolbarColor, other.toolbarColor) && _deepEquals(closeButtonStyle, other.closeButtonStyle) && _deepEquals(closeButtonPosition, other.closeButtonPosition) && _deepEquals(shareButtonEnabled, other.shareButtonEnabled) && _deepEquals(showTitleEnabled, other.showTitleEnabled) && _deepEquals(urlBarHidingEnabled, other.urlBarHidingEnabled) && _deepEquals(bookmarksButtonEnabled, other.bookmarksButtonEnabled) && _deepEquals(downloadsButtonEnabled, other.downloadsButtonEnabled) && _deepEquals(navigationBarColor, other.navigationBarColor) && _deepEquals(navigationBarDividerColor, other.navigationBarDividerColor) && _deepEquals(colorScheme, other.colorScheme);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeAndroidBrowserOptions(toolbarColor: $toolbarColor, closeButtonStyle: $closeButtonStyle, closeButtonPosition: $closeButtonPosition, shareButtonEnabled: $shareButtonEnabled, showTitleEnabled: $showTitleEnabled, urlBarHidingEnabled: $urlBarHidingEnabled, bookmarksButtonEnabled: $bookmarksButtonEnabled, downloadsButtonEnabled: $downloadsButtonEnabled, navigationBarColor: $navigationBarColor, navigationBarDividerColor: $navigationBarDividerColor, colorScheme: $colorScheme)';
  }
}

/// Every field is `null` by default. `null` isn't resolved to a fallback
/// anywhere in Dart — it crosses the channel as-is, and the native side
/// decides what "unset" means (usually: don't touch the corresponding
/// `SFSafariViewController` property at all, so the OS's own live default
/// applies). This is deliberate: hardcoding a guess at "the platform
/// default" in Dart can go stale the moment Apple changes it, silently
/// changing behavior for every integrator who never touched that field.
///
/// Same fixed-position wire encoding as [NativeAndroidBrowserOptions] —
/// append future fields at the end, never insert.
class NativeIosBrowserOptions {
  NativeIosBrowserOptions({
    this.dismissButtonStyle,
    this.barCollapsingEnabled,
    this.presentationStyle,
    this.colorScheme,
  });

  NativeDismissButtonStyle? dismissButtonStyle;

  /// Only has a visible effect when [presentationStyle] is `fullScreen` —
  /// confirmed by hands-on testing that `pageSheet` keeps the bars pinned
  /// regardless of this setting.
  bool? barCollapsingEnabled;

  NativePresentationStyle? presentationStyle;

  NativeBrowserColorScheme? colorScheme;

  List<Object?> _toList() {
    return <Object?>[
      dismissButtonStyle,
      barCollapsingEnabled,
      presentationStyle,
      colorScheme,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeIosBrowserOptions decode(Object result) {
    result as List<Object?>;
    return NativeIosBrowserOptions(
      dismissButtonStyle: result[0] as NativeDismissButtonStyle?,
      barCollapsingEnabled: result[1] as bool?,
      presentationStyle: result[2] as NativePresentationStyle?,
      colorScheme: result[3] as NativeBrowserColorScheme?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeIosBrowserOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(dismissButtonStyle, other.dismissButtonStyle) && _deepEquals(barCollapsingEnabled, other.barCollapsingEnabled) && _deepEquals(presentationStyle, other.presentationStyle) && _deepEquals(colorScheme, other.colorScheme);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeIosBrowserOptions(dismissButtonStyle: $dismissButtonStyle, barCollapsingEnabled: $barCollapsingEnabled, presentationStyle: $presentationStyle, colorScheme: $colorScheme)';
  }
}

/// Mirrors the native `CheckoutResult`.
class NativeCheckoutResult {
  NativeCheckoutResult({
    required this.status,
    this.paymentId,
    this.subscriptionId,
    this.licenseKeys,
    this.customerEmail,
    required this.raw,
  });

  NativeCheckoutStatus status;

  String? paymentId;

  String? subscriptionId;

  List<String>? licenseKeys;

  String? customerEmail;

  /// All query parameters from the return_url, verbatim.
  Map<String, String> raw;

  List<Object?> _toList() {
    return <Object?>[
      status,
      paymentId,
      subscriptionId,
      licenseKeys,
      customerEmail,
      raw,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeCheckoutResult decode(Object result) {
    result as List<Object?>;
    return NativeCheckoutResult(
      status: result[0]! as NativeCheckoutStatus,
      paymentId: result[1] as String?,
      subscriptionId: result[2] as String?,
      licenseKeys: (result[3] as List<Object?>?)?.cast<String>(),
      customerEmail: result[4] as String?,
      raw: (result[5]! as Map<Object?, Object?>).cast<String, String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeCheckoutResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(status, other.status) && _deepEquals(paymentId, other.paymentId) && _deepEquals(subscriptionId, other.subscriptionId) && _deepEquals(licenseKeys, other.licenseKeys) && _deepEquals(customerEmail, other.customerEmail) && _deepEquals(raw, other.raw);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeCheckoutResult(status: $status, paymentId: $paymentId, subscriptionId: $subscriptionId, licenseKeys: $licenseKeys, customerEmail: $customerEmail, raw: $raw)';
  }
}

/// Mirrors the native `AbandonedSession`.
class NativeAbandonedSession {
  NativeAbandonedSession({
    required this.sessionId,
    required this.createdAtMillis,
  });

  String sessionId;

  /// Milliseconds since the Unix epoch (UTC).
  int createdAtMillis;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      createdAtMillis,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeAbandonedSession decode(Object result) {
    result as List<Object?>;
    return NativeAbandonedSession(
      sessionId: result[0]! as String,
      createdAtMillis: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAbandonedSession || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(createdAtMillis, other.createdAtMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeAbandonedSession(sessionId: $sessionId, createdAtMillis: $createdAtMillis)';
  }
}

class NativeCheckoutEvent {
  NativeCheckoutEvent({
    required this.type,
  });

  NativeEventType type;

  List<Object?> _toList() {
    return <Object?>[
      type,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeCheckoutEvent decode(Object result) {
    result as List<Object?>;
    return NativeCheckoutEvent(
      type: result[0]! as NativeEventType,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeCheckoutEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeCheckoutEvent(type: $type)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NativeCheckoutStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is NativeCloseButtonStyle) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is NativeCloseButtonPosition) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is NativeDismissButtonStyle) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is NativePresentationStyle) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is NativeBrowserColorScheme) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is NativeEventType) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    }    else if (value is StartRequest) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is NativeBrowserCustomization) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is NativeAndroidBrowserOptions) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is NativeIosBrowserOptions) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is NativeCheckoutResult) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is NativeAbandonedSession) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is NativeCheckoutEvent) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeCheckoutStatus.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeCloseButtonStyle.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeCloseButtonPosition.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeDismissButtonStyle.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativePresentationStyle.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeBrowserColorScheme.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeEventType.values[value];
      case 136:
        return StartRequest.decode(readValue(buffer)!);
      case 137:
        return NativeBrowserCustomization.decode(readValue(buffer)!);
      case 138:
        return NativeAndroidBrowserOptions.decode(readValue(buffer)!);
      case 139:
        return NativeIosBrowserOptions.decode(readValue(buffer)!);
      case 140:
        return NativeCheckoutResult.decode(readValue(buffer)!);
      case 141:
        return NativeAbandonedSession.decode(readValue(buffer)!);
      case 142:
        return NativeCheckoutEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Implemented natively (Swift/Kotlin), called from Dart. Presents an
/// `SFSafariViewController` sheet on iOS, a Custom Tab on Android.
///
/// Errors are surfaced as PlatformException with `code` set to one of the
/// shared native error codes: INVALID_CHECKOUT_URL, INVALID_RETURN_URL,
/// ALREADY_IN_PROGRESS, PLATFORM_ERROR.
class DodoCheckoutHostApi {
  /// Constructor for [DodoCheckoutHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DodoCheckoutHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Presents the checkout and completes when it resolves. Lifecycle events
  /// for this call are delivered via [DodoCheckoutFlutterApi.onCheckoutEvent]
  /// for the call's duration.
  Future<NativeCheckoutResult> start(StartRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutHostApi.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeCheckoutResult;
  }

  Future<NativeAbandonedSession?> getAbandonedSession() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutHostApi.getAbandonedSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as NativeAbandonedSession?;
  }

  Future<void> clearAbandonedSession() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutHostApi.clearAbandonedSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// iOS only — forward incoming URLs here from your app's own URL-handling.
  /// Required: `SFSafariViewController` has no in-process way to catch its
  /// own return URL. No-op returning `false` on Android (Custom Tabs there is
  /// fully self-contained via Activities). Returns `true` if the URL belonged
  /// to an in-flight checkout.
  Future<bool> handleOpenURL(String url) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutHostApi.handleOpenURL$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[url]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }
}

/// Implemented in Dart, called from native. Delivers lifecycle events for
/// whichever checkout is currently in flight — logging/analytics only.
abstract class DodoCheckoutFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onCheckoutEvent(NativeCheckoutEvent event);

  static void setUp(DodoCheckoutFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutFlutterApi.onCheckoutEvent$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final NativeCheckoutEvent arg_event = args[0]! as NativeCheckoutEvent;
          try {
            api.onCheckoutEvent(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
