// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Mirrors `CheckoutStatus` in the native cores.
enum NativeCheckoutStatus: Int, CaseIterable {
  case succeeded = 0
  case failed = 1
  case cancelled = 2
  case pending = 3
  case expired = 4
}

/// Mirrors `CheckoutEvent` in the native cores. Lifecycle-only — never used
/// to decide the checkout outcome.
enum NativeEventType: Int, CaseIterable {
  case opened = 0
  case returnReceived = 1
  case closed = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct StartRequest: Hashable, CustomStringConvertible {
  /// Absolute session URL from the merchant backend.
  var checkoutUrl: String
  /// Absolute URL the native SDK watches for. Its scheme must be registered
  /// as a URL type in Info.plist (iOS) / an intent-filter on the redirect
  /// activity (Android), so the OS routes the checkout return back to this
  /// app.
  var returnUrl: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StartRequest? {
    let checkoutUrl = pigeonVar_list[0] as! String
    let returnUrl = pigeonVar_list[1] as! String

    return StartRequest(
      checkoutUrl: checkoutUrl,
      returnUrl: returnUrl
    )
  }
  func toList() -> [Any?] {
    return [
      checkoutUrl,
      returnUrl,
    ]
  }
  static func == (lhs: StartRequest, rhs: StartRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.checkoutUrl, rhs.checkoutUrl) && MessagesPigeonInternal.deepEquals(lhs.returnUrl, rhs.returnUrl)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("StartRequest")
    MessagesPigeonInternal.deepHash(value: checkoutUrl, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: returnUrl, hasher: &hasher)
  }

  public var description: String {
    return "StartRequest(checkoutUrl: \(String(describing: checkoutUrl)), returnUrl: \(String(describing: returnUrl)))"
  }
}

/// Mirrors the native `CheckoutResult`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeCheckoutResult: Hashable, CustomStringConvertible {
  var status: NativeCheckoutStatus
  var paymentId: String? = nil
  var subscriptionId: String? = nil
  var licenseKeys: [String]? = nil
  var customerEmail: String? = nil
  /// All query parameters from the return_url, verbatim.
  var raw: [String: String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeCheckoutResult? {
    let status = pigeonVar_list[0] as! NativeCheckoutStatus
    let paymentId: String? = nilOrValue(pigeonVar_list[1])
    let subscriptionId: String? = nilOrValue(pigeonVar_list[2])
    let licenseKeys: [String]? = nilOrValue(pigeonVar_list[3])
    let customerEmail: String? = nilOrValue(pigeonVar_list[4])
    let raw = pigeonVar_list[5] as! [String: String]

    return NativeCheckoutResult(
      status: status,
      paymentId: paymentId,
      subscriptionId: subscriptionId,
      licenseKeys: licenseKeys,
      customerEmail: customerEmail,
      raw: raw
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      paymentId,
      subscriptionId,
      licenseKeys,
      customerEmail,
      raw,
    ]
  }
  static func == (lhs: NativeCheckoutResult, rhs: NativeCheckoutResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.status, rhs.status) && MessagesPigeonInternal.deepEquals(lhs.paymentId, rhs.paymentId) && MessagesPigeonInternal.deepEquals(lhs.subscriptionId, rhs.subscriptionId) && MessagesPigeonInternal.deepEquals(lhs.licenseKeys, rhs.licenseKeys) && MessagesPigeonInternal.deepEquals(lhs.customerEmail, rhs.customerEmail) && MessagesPigeonInternal.deepEquals(lhs.raw, rhs.raw)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeCheckoutResult")
    MessagesPigeonInternal.deepHash(value: status, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: paymentId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: subscriptionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: licenseKeys, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: customerEmail, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: raw, hasher: &hasher)
  }

  public var description: String {
    return "NativeCheckoutResult(status: \(String(describing: status)), paymentId: \(String(describing: paymentId)), subscriptionId: \(String(describing: subscriptionId)), licenseKeys: \(String(describing: licenseKeys)), customerEmail: \(String(describing: customerEmail)), raw: \(String(describing: raw)))"
  }
}

/// Mirrors the native `AbandonedSession`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeAbandonedSession: Hashable, CustomStringConvertible {
  var sessionId: String
  /// Milliseconds since the Unix epoch (UTC).
  var createdAtMillis: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAbandonedSession? {
    let sessionId = pigeonVar_list[0] as! String
    let createdAtMillis = pigeonVar_list[1] as! Int64

    return NativeAbandonedSession(
      sessionId: sessionId,
      createdAtMillis: createdAtMillis
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      createdAtMillis,
    ]
  }
  static func == (lhs: NativeAbandonedSession, rhs: NativeAbandonedSession) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && MessagesPigeonInternal.deepEquals(lhs.createdAtMillis, rhs.createdAtMillis)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAbandonedSession")
    MessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: createdAtMillis, hasher: &hasher)
  }

  public var description: String {
    return "NativeAbandonedSession(sessionId: \(String(describing: sessionId)), createdAtMillis: \(String(describing: createdAtMillis)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeCheckoutEvent: Hashable, CustomStringConvertible {
  var type: NativeEventType


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeCheckoutEvent? {
    let type = pigeonVar_list[0] as! NativeEventType

    return NativeCheckoutEvent(
      type: type
    )
  }
  func toList() -> [Any?] {
    return [
      type
    ]
  }
  static func == (lhs: NativeCheckoutEvent, rhs: NativeCheckoutEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.type, rhs.type)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeCheckoutEvent")
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
  }

  public var description: String {
    return "NativeCheckoutEvent(type: \(String(describing: type)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeCheckoutStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeEventType(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return StartRequest.fromList(self.readValue() as! [Any?])
    case 132:
      return NativeCheckoutResult.fromList(self.readValue() as! [Any?])
    case 133:
      return NativeAbandonedSession.fromList(self.readValue() as! [Any?])
    case 134:
      return NativeCheckoutEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeCheckoutStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeEventType {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? StartRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NativeCheckoutResult {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAbandonedSession {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? NativeCheckoutEvent {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Implemented natively (Swift/Kotlin), called from Dart. Presents an
/// `SFSafariViewController` sheet on iOS, a Custom Tab on Android.
///
/// Errors are surfaced as PlatformException with `code` set to one of the
/// shared native error codes: INVALID_CHECKOUT_URL, INVALID_RETURN_URL,
/// ALREADY_IN_PROGRESS, PLATFORM_ERROR.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DodoCheckoutHostApi {
  /// Presents the checkout and completes when it resolves. Lifecycle events
  /// for this call are delivered via [DodoCheckoutFlutterApi.onCheckoutEvent]
  /// for the call's duration.
  func start(request: StartRequest, completion: @escaping (Result<NativeCheckoutResult, Error>) -> Void)
  func getAbandonedSession() throws -> NativeAbandonedSession?
  func clearAbandonedSession() throws
  /// iOS only — forward incoming URLs here from your app's own URL-handling.
  /// Required: `SFSafariViewController` has no in-process way to catch its
  /// own return URL. No-op returning `false` on Android (Custom Tabs there is
  /// fully self-contained via Activities). Returns `true` if the URL belonged
  /// to an in-flight checkout.
  func handleOpenURL(url: String) throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DodoCheckoutHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `DodoCheckoutHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DodoCheckoutHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Presents the checkout and completes when it resolves. Lifecycle events
    /// for this call are delivered via [DodoCheckoutFlutterApi.onCheckoutEvent]
    /// for the call's duration.
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! StartRequest
        api.start(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    let getAbandonedSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutHostApi.getAbandonedSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAbandonedSessionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAbandonedSession()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAbandonedSessionChannel.setMessageHandler(nil)
    }
    let clearAbandonedSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutHostApi.clearAbandonedSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearAbandonedSessionChannel.setMessageHandler { _, reply in
        do {
          try api.clearAbandonedSession()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearAbandonedSessionChannel.setMessageHandler(nil)
    }
    /// iOS only — forward incoming URLs here from your app's own URL-handling.
    /// Required: `SFSafariViewController` has no in-process way to catch its
    /// own return URL. No-op returning `false` on Android (Custom Tabs there is
    /// fully self-contained via Activities). Returns `true` if the URL belonged
    /// to an in-flight checkout.
    let handleOpenURLChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutHostApi.handleOpenURL\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      handleOpenURLChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        do {
          let result = try api.handleOpenURL(url: urlArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      handleOpenURLChannel.setMessageHandler(nil)
    }
  }
}

/// Implemented in Dart, called from native. Delivers lifecycle events for
/// whichever checkout is currently in flight — logging/analytics only.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol DodoCheckoutFlutterApiProtocol {
  func onCheckoutEvent(event eventArg: NativeCheckoutEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class DodoCheckoutFlutterApi: DodoCheckoutFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onCheckoutEvent(event eventArg: NativeCheckoutEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutFlutterApi.onCheckoutEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
