// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Mirrors `CheckoutStatus` in the native cores.
enum NativeCheckoutStatus: Int, CaseIterable {
  case succeeded = 0
  case failed = 1
  case cancelled = 2
  case pending = 3
  case expired = 4
}

/// `standard` (not `default` — a reserved Dart keyword) is the system "X"
/// icon on Android; `back` is a back-arrow icon the SDK draws itself. No
/// iOS equivalent — see [NativeDismissButtonStyle] for iOS's dismiss button.
enum NativeCloseButtonStyle: Int, CaseIterable {
  case standard = 0
  case back = 1
}

enum NativeCloseButtonPosition: Int, CaseIterable {
  case start = 0
  case end = 1
}

/// Mirrors `SFSafariViewController.DismissButtonStyle`. No Android
/// equivalent — see [NativeCloseButtonStyle] for Android's close button.
enum NativeDismissButtonStyle: Int, CaseIterable {
  case done = 0
  case close = 1
  case cancel = 2
}

/// Mirrors `UIViewController.modalPresentationStyle` as used to present the
/// checkout sheet. No Android equivalent — Custom Tabs has no comparable
/// page-sheet-vs-full-screen distinction in this SDK.
enum NativePresentationStyle: Int, CaseIterable {
  case pageSheet = 0
  case fullScreen = 1
}

/// Forces the browser's light/dark appearance regardless of the system
/// setting. Exists independently on `android` and `ios` (not shared) even
/// though the values are identical, matching every other field here.
enum NativeBrowserColorScheme: Int, CaseIterable {
  case system = 0
  case light = 1
  case dark = 2
}

/// Mirrors `CheckoutEvent` in the native cores. Lifecycle-only — never used
/// to decide the checkout outcome.
enum NativeEventType: Int, CaseIterable {
  case opened = 0
  case returnReceived = 1
  case closed = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct StartRequest: Hashable, CustomStringConvertible {
  /// Absolute session URL from the merchant backend.
  var checkoutUrl: String
  /// Absolute URL the native SDK watches for. Its scheme must be registered
  /// as a URL type in Info.plist (iOS) / an intent-filter on the redirect
  /// activity (Android), so the OS routes the checkout return back to this
  /// app.
  var returnUrl: String
  /// Appearance customization for the checkout browser.
  var customization: NativeBrowserCustomization? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StartRequest? {
    let checkoutUrl = pigeonVar_list[0] as! String
    let returnUrl = pigeonVar_list[1] as! String
    let customization: NativeBrowserCustomization? = nilOrValue(pigeonVar_list[2])

    return StartRequest(
      checkoutUrl: checkoutUrl,
      returnUrl: returnUrl,
      customization: customization
    )
  }
  func toList() -> [Any?] {
    return [
      checkoutUrl,
      returnUrl,
      customization,
    ]
  }
  static func == (lhs: StartRequest, rhs: StartRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.checkoutUrl, rhs.checkoutUrl) && MessagesPigeonInternal.deepEquals(lhs.returnUrl, rhs.returnUrl) && MessagesPigeonInternal.deepEquals(lhs.customization, rhs.customization)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("StartRequest")
    MessagesPigeonInternal.deepHash(value: checkoutUrl, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: returnUrl, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: customization, hasher: &hasher)
  }

  public var description: String {
    return "StartRequest(checkoutUrl: \(String(describing: checkoutUrl)), returnUrl: \(String(describing: returnUrl)), customization: \(String(describing: customization)))"
  }
}

/// Mirrors the native `BrowserCustomization`. `android`/`ios` carry options
/// that only exist on that one platform — native only ever reads its own
/// bag, so this crosses both platforms from one Dart type without either
/// side seeing the other's fields.
///
/// No shared/top-level fields: `toolbarColor` was originally shared, but
/// iOS's equivalent (`preferredBarTintColor`) is deprecated as of iOS 26
/// with no replacement and confirmed to have no visible effect there — not
/// worth a color knob that's already inert on the majority of iOS devices.
/// Same reasoning killed iOS's `controlTintColor` outright (it rested on
/// the identically-deprecated `preferredControlTintColor`).
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeBrowserCustomization: Hashable, CustomStringConvertible {
  var android: NativeAndroidBrowserOptions? = nil
  var ios: NativeIosBrowserOptions? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeBrowserCustomization? {
    let android: NativeAndroidBrowserOptions? = nilOrValue(pigeonVar_list[0])
    let ios: NativeIosBrowserOptions? = nilOrValue(pigeonVar_list[1])

    return NativeBrowserCustomization(
      android: android,
      ios: ios
    )
  }
  func toList() -> [Any?] {
    return [
      android,
      ios,
    ]
  }
  static func == (lhs: NativeBrowserCustomization, rhs: NativeBrowserCustomization) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.android, rhs.android) && MessagesPigeonInternal.deepEquals(lhs.ios, rhs.ios)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeBrowserCustomization")
    MessagesPigeonInternal.deepHash(value: android, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: ios, hasher: &hasher)
  }

  public var description: String {
    return "NativeBrowserCustomization(android: \(String(describing: android)), ios: \(String(describing: ios)))"
  }
}

/// Every field is `null` by default. `null` isn't resolved to a fallback
/// anywhere in Dart — it crosses the channel as-is, and the native side
/// decides what "unset" means (usually: don't call the corresponding
/// `CustomTabsIntent.Builder` setter at all, so the Custom Tab host's own
/// live default applies). This is deliberate: hardcoding a guess at "the
/// platform default" in Dart can go stale the moment the host changes it,
/// silently changing behavior for every integrator who never touched that
/// field.
///
/// Pigeon encodes this class as a fixed-position list, not a keyed map —
/// `decode()` reads `result[0]`, `result[1]`, ... by index, matching
/// declaration order exactly. Future fields must be appended at the end,
/// never inserted, or every field after the insertion point silently reads
/// the wrong value. Regenerate all three codegen targets together after any
/// change (`dart run pigeon --input pigeons/messages.dart`).
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeAndroidBrowserOptions: Hashable, CustomStringConvertible {
  /// ARGB, i.e. `Color.toARGB32()`.
  var toolbarColor: Int64? = nil
  var closeButtonStyle: NativeCloseButtonStyle? = nil
  var closeButtonPosition: NativeCloseButtonPosition? = nil
  /// Hides the toolbar's share icon when `false`.
  var shareButtonEnabled: Bool? = nil
  var showTitleEnabled: Bool? = nil
  var urlBarHidingEnabled: Bool? = nil
  var bookmarksButtonEnabled: Bool? = nil
  var downloadsButtonEnabled: Bool? = nil
  var secondaryToolbarColor: Int64? = nil
  var navigationBarColor: Int64? = nil
  var navigationBarDividerColor: Int64? = nil
  var colorScheme: NativeBrowserColorScheme? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAndroidBrowserOptions? {
    let toolbarColor: Int64? = nilOrValue(pigeonVar_list[0])
    let closeButtonStyle: NativeCloseButtonStyle? = nilOrValue(pigeonVar_list[1])
    let closeButtonPosition: NativeCloseButtonPosition? = nilOrValue(pigeonVar_list[2])
    let shareButtonEnabled: Bool? = nilOrValue(pigeonVar_list[3])
    let showTitleEnabled: Bool? = nilOrValue(pigeonVar_list[4])
    let urlBarHidingEnabled: Bool? = nilOrValue(pigeonVar_list[5])
    let bookmarksButtonEnabled: Bool? = nilOrValue(pigeonVar_list[6])
    let downloadsButtonEnabled: Bool? = nilOrValue(pigeonVar_list[7])
    let secondaryToolbarColor: Int64? = nilOrValue(pigeonVar_list[8])
    let navigationBarColor: Int64? = nilOrValue(pigeonVar_list[9])
    let navigationBarDividerColor: Int64? = nilOrValue(pigeonVar_list[10])
    let colorScheme: NativeBrowserColorScheme? = nilOrValue(pigeonVar_list[11])

    return NativeAndroidBrowserOptions(
      toolbarColor: toolbarColor,
      closeButtonStyle: closeButtonStyle,
      closeButtonPosition: closeButtonPosition,
      shareButtonEnabled: shareButtonEnabled,
      showTitleEnabled: showTitleEnabled,
      urlBarHidingEnabled: urlBarHidingEnabled,
      bookmarksButtonEnabled: bookmarksButtonEnabled,
      downloadsButtonEnabled: downloadsButtonEnabled,
      secondaryToolbarColor: secondaryToolbarColor,
      navigationBarColor: navigationBarColor,
      navigationBarDividerColor: navigationBarDividerColor,
      colorScheme: colorScheme
    )
  }
  func toList() -> [Any?] {
    return [
      toolbarColor,
      closeButtonStyle,
      closeButtonPosition,
      shareButtonEnabled,
      showTitleEnabled,
      urlBarHidingEnabled,
      bookmarksButtonEnabled,
      downloadsButtonEnabled,
      secondaryToolbarColor,
      navigationBarColor,
      navigationBarDividerColor,
      colorScheme,
    ]
  }
  static func == (lhs: NativeAndroidBrowserOptions, rhs: NativeAndroidBrowserOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.toolbarColor, rhs.toolbarColor) && MessagesPigeonInternal.deepEquals(lhs.closeButtonStyle, rhs.closeButtonStyle) && MessagesPigeonInternal.deepEquals(lhs.closeButtonPosition, rhs.closeButtonPosition) && MessagesPigeonInternal.deepEquals(lhs.shareButtonEnabled, rhs.shareButtonEnabled) && MessagesPigeonInternal.deepEquals(lhs.showTitleEnabled, rhs.showTitleEnabled) && MessagesPigeonInternal.deepEquals(lhs.urlBarHidingEnabled, rhs.urlBarHidingEnabled) && MessagesPigeonInternal.deepEquals(lhs.bookmarksButtonEnabled, rhs.bookmarksButtonEnabled) && MessagesPigeonInternal.deepEquals(lhs.downloadsButtonEnabled, rhs.downloadsButtonEnabled) && MessagesPigeonInternal.deepEquals(lhs.secondaryToolbarColor, rhs.secondaryToolbarColor) && MessagesPigeonInternal.deepEquals(lhs.navigationBarColor, rhs.navigationBarColor) && MessagesPigeonInternal.deepEquals(lhs.navigationBarDividerColor, rhs.navigationBarDividerColor) && MessagesPigeonInternal.deepEquals(lhs.colorScheme, rhs.colorScheme)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAndroidBrowserOptions")
    MessagesPigeonInternal.deepHash(value: toolbarColor, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: closeButtonStyle, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: closeButtonPosition, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: shareButtonEnabled, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: showTitleEnabled, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: urlBarHidingEnabled, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bookmarksButtonEnabled, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: downloadsButtonEnabled, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: secondaryToolbarColor, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: navigationBarColor, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: navigationBarDividerColor, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: colorScheme, hasher: &hasher)
  }

  public var description: String {
    return "NativeAndroidBrowserOptions(toolbarColor: \(String(describing: toolbarColor)), closeButtonStyle: \(String(describing: closeButtonStyle)), closeButtonPosition: \(String(describing: closeButtonPosition)), shareButtonEnabled: \(String(describing: shareButtonEnabled)), showTitleEnabled: \(String(describing: showTitleEnabled)), urlBarHidingEnabled: \(String(describing: urlBarHidingEnabled)), bookmarksButtonEnabled: \(String(describing: bookmarksButtonEnabled)), downloadsButtonEnabled: \(String(describing: downloadsButtonEnabled)), secondaryToolbarColor: \(String(describing: secondaryToolbarColor)), navigationBarColor: \(String(describing: navigationBarColor)), navigationBarDividerColor: \(String(describing: navigationBarDividerColor)), colorScheme: \(String(describing: colorScheme)))"
  }
}

/// Every field is `null` by default. `null` isn't resolved to a fallback
/// anywhere in Dart — it crosses the channel as-is, and the native side
/// decides what "unset" means (usually: don't touch the corresponding
/// `SFSafariViewController` property at all, so the OS's own live default
/// applies). This is deliberate: hardcoding a guess at "the platform
/// default" in Dart can go stale the moment Apple changes it, silently
/// changing behavior for every integrator who never touched that field.
///
/// Same fixed-position wire encoding as [NativeAndroidBrowserOptions] —
/// append future fields at the end, never insert.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeIosBrowserOptions: Hashable, CustomStringConvertible {
  var dismissButtonStyle: NativeDismissButtonStyle? = nil
  /// Only has a visible effect when [presentationStyle] is `fullScreen` —
  /// confirmed by hands-on testing that `pageSheet` keeps the bars pinned
  /// regardless of this setting.
  var barCollapsingEnabled: Bool? = nil
  var presentationStyle: NativePresentationStyle? = nil
  var colorScheme: NativeBrowserColorScheme? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeIosBrowserOptions? {
    let dismissButtonStyle: NativeDismissButtonStyle? = nilOrValue(pigeonVar_list[0])
    let barCollapsingEnabled: Bool? = nilOrValue(pigeonVar_list[1])
    let presentationStyle: NativePresentationStyle? = nilOrValue(pigeonVar_list[2])
    let colorScheme: NativeBrowserColorScheme? = nilOrValue(pigeonVar_list[3])

    return NativeIosBrowserOptions(
      dismissButtonStyle: dismissButtonStyle,
      barCollapsingEnabled: barCollapsingEnabled,
      presentationStyle: presentationStyle,
      colorScheme: colorScheme
    )
  }
  func toList() -> [Any?] {
    return [
      dismissButtonStyle,
      barCollapsingEnabled,
      presentationStyle,
      colorScheme,
    ]
  }
  static func == (lhs: NativeIosBrowserOptions, rhs: NativeIosBrowserOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.dismissButtonStyle, rhs.dismissButtonStyle) && MessagesPigeonInternal.deepEquals(lhs.barCollapsingEnabled, rhs.barCollapsingEnabled) && MessagesPigeonInternal.deepEquals(lhs.presentationStyle, rhs.presentationStyle) && MessagesPigeonInternal.deepEquals(lhs.colorScheme, rhs.colorScheme)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeIosBrowserOptions")
    MessagesPigeonInternal.deepHash(value: dismissButtonStyle, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: barCollapsingEnabled, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: presentationStyle, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: colorScheme, hasher: &hasher)
  }

  public var description: String {
    return "NativeIosBrowserOptions(dismissButtonStyle: \(String(describing: dismissButtonStyle)), barCollapsingEnabled: \(String(describing: barCollapsingEnabled)), presentationStyle: \(String(describing: presentationStyle)), colorScheme: \(String(describing: colorScheme)))"
  }
}

/// Mirrors the native `CheckoutResult`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeCheckoutResult: Hashable, CustomStringConvertible {
  var status: NativeCheckoutStatus
  var paymentId: String? = nil
  var subscriptionId: String? = nil
  var licenseKeys: [String]? = nil
  var customerEmail: String? = nil
  /// All query parameters from the return_url, verbatim.
  var raw: [String: String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeCheckoutResult? {
    let status = pigeonVar_list[0] as! NativeCheckoutStatus
    let paymentId: String? = nilOrValue(pigeonVar_list[1])
    let subscriptionId: String? = nilOrValue(pigeonVar_list[2])
    let licenseKeys: [String]? = nilOrValue(pigeonVar_list[3])
    let customerEmail: String? = nilOrValue(pigeonVar_list[4])
    let raw = pigeonVar_list[5] as! [String: String]

    return NativeCheckoutResult(
      status: status,
      paymentId: paymentId,
      subscriptionId: subscriptionId,
      licenseKeys: licenseKeys,
      customerEmail: customerEmail,
      raw: raw
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      paymentId,
      subscriptionId,
      licenseKeys,
      customerEmail,
      raw,
    ]
  }
  static func == (lhs: NativeCheckoutResult, rhs: NativeCheckoutResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.status, rhs.status) && MessagesPigeonInternal.deepEquals(lhs.paymentId, rhs.paymentId) && MessagesPigeonInternal.deepEquals(lhs.subscriptionId, rhs.subscriptionId) && MessagesPigeonInternal.deepEquals(lhs.licenseKeys, rhs.licenseKeys) && MessagesPigeonInternal.deepEquals(lhs.customerEmail, rhs.customerEmail) && MessagesPigeonInternal.deepEquals(lhs.raw, rhs.raw)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeCheckoutResult")
    MessagesPigeonInternal.deepHash(value: status, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: paymentId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: subscriptionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: licenseKeys, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: customerEmail, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: raw, hasher: &hasher)
  }

  public var description: String {
    return "NativeCheckoutResult(status: \(String(describing: status)), paymentId: \(String(describing: paymentId)), subscriptionId: \(String(describing: subscriptionId)), licenseKeys: \(String(describing: licenseKeys)), customerEmail: \(String(describing: customerEmail)), raw: \(String(describing: raw)))"
  }
}

/// Mirrors the native `AbandonedSession`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeAbandonedSession: Hashable, CustomStringConvertible {
  var sessionId: String
  /// Milliseconds since the Unix epoch (UTC).
  var createdAtMillis: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAbandonedSession? {
    let sessionId = pigeonVar_list[0] as! String
    let createdAtMillis = pigeonVar_list[1] as! Int64

    return NativeAbandonedSession(
      sessionId: sessionId,
      createdAtMillis: createdAtMillis
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      createdAtMillis,
    ]
  }
  static func == (lhs: NativeAbandonedSession, rhs: NativeAbandonedSession) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && MessagesPigeonInternal.deepEquals(lhs.createdAtMillis, rhs.createdAtMillis)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAbandonedSession")
    MessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: createdAtMillis, hasher: &hasher)
  }

  public var description: String {
    return "NativeAbandonedSession(sessionId: \(String(describing: sessionId)), createdAtMillis: \(String(describing: createdAtMillis)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeCheckoutEvent: Hashable, CustomStringConvertible {
  var type: NativeEventType


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeCheckoutEvent? {
    let type = pigeonVar_list[0] as! NativeEventType

    return NativeCheckoutEvent(
      type: type
    )
  }
  func toList() -> [Any?] {
    return [
      type
    ]
  }
  static func == (lhs: NativeCheckoutEvent, rhs: NativeCheckoutEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.type, rhs.type)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeCheckoutEvent")
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
  }

  public var description: String {
    return "NativeCheckoutEvent(type: \(String(describing: type)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeCheckoutStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeCloseButtonStyle(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeCloseButtonPosition(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeDismissButtonStyle(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativePresentationStyle(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeBrowserColorScheme(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeEventType(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      return StartRequest.fromList(self.readValue() as! [Any?])
    case 137:
      return NativeBrowserCustomization.fromList(self.readValue() as! [Any?])
    case 138:
      return NativeAndroidBrowserOptions.fromList(self.readValue() as! [Any?])
    case 139:
      return NativeIosBrowserOptions.fromList(self.readValue() as! [Any?])
    case 140:
      return NativeCheckoutResult.fromList(self.readValue() as! [Any?])
    case 141:
      return NativeAbandonedSession.fromList(self.readValue() as! [Any?])
    case 142:
      return NativeCheckoutEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeCheckoutStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeCloseButtonStyle {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeCloseButtonPosition {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeDismissButtonStyle {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativePresentationStyle {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeBrowserColorScheme {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeEventType {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? StartRequest {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? NativeBrowserCustomization {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAndroidBrowserOptions {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? NativeIosBrowserOptions {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? NativeCheckoutResult {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAbandonedSession {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? NativeCheckoutEvent {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Implemented natively (Swift/Kotlin), called from Dart. Presents an
/// `SFSafariViewController` sheet on iOS, a Custom Tab on Android.
///
/// Errors are surfaced as PlatformException with `code` set to one of the
/// shared native error codes: INVALID_CHECKOUT_URL, INVALID_RETURN_URL,
/// ALREADY_IN_PROGRESS, PLATFORM_ERROR.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DodoCheckoutHostApi {
  /// Presents the checkout and completes when it resolves. Lifecycle events
  /// for this call are delivered via [DodoCheckoutFlutterApi.onCheckoutEvent]
  /// for the call's duration.
  func start(request: StartRequest, completion: @escaping (Result<NativeCheckoutResult, Error>) -> Void)
  func getAbandonedSession() throws -> NativeAbandonedSession?
  func clearAbandonedSession() throws
  /// iOS only — forward incoming URLs here from your app's own URL-handling.
  /// Required: `SFSafariViewController` has no in-process way to catch its
  /// own return URL. No-op returning `false` on Android (Custom Tabs there is
  /// fully self-contained via Activities). Returns `true` if the URL belonged
  /// to an in-flight checkout.
  func handleOpenURL(url: String) throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DodoCheckoutHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `DodoCheckoutHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DodoCheckoutHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Presents the checkout and completes when it resolves. Lifecycle events
    /// for this call are delivered via [DodoCheckoutFlutterApi.onCheckoutEvent]
    /// for the call's duration.
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! StartRequest
        api.start(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    let getAbandonedSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutHostApi.getAbandonedSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAbandonedSessionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAbandonedSession()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAbandonedSessionChannel.setMessageHandler(nil)
    }
    let clearAbandonedSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutHostApi.clearAbandonedSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearAbandonedSessionChannel.setMessageHandler { _, reply in
        do {
          try api.clearAbandonedSession()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearAbandonedSessionChannel.setMessageHandler(nil)
    }
    /// iOS only — forward incoming URLs here from your app's own URL-handling.
    /// Required: `SFSafariViewController` has no in-process way to catch its
    /// own return URL. No-op returning `false` on Android (Custom Tabs there is
    /// fully self-contained via Activities). Returns `true` if the URL belonged
    /// to an in-flight checkout.
    let handleOpenURLChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutHostApi.handleOpenURL\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      handleOpenURLChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        do {
          let result = try api.handleOpenURL(url: urlArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      handleOpenURLChannel.setMessageHandler(nil)
    }
  }
}

/// Implemented in Dart, called from native. Delivers lifecycle events for
/// whichever checkout is currently in flight — logging/analytics only.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol DodoCheckoutFlutterApiProtocol {
  func onCheckoutEvent(event eventArg: NativeCheckoutEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class DodoCheckoutFlutterApi: DodoCheckoutFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onCheckoutEvent(event eventArg: NativeCheckoutEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutFlutterApi.onCheckoutEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
