// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.dodopayments.checkout_flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Mirrors `CheckoutStatus` in the native cores. */
enum class NativeCheckoutStatus(val raw: Int) {
  SUCCEEDED(0),
  FAILED(1),
  CANCELLED(2),
  PENDING(3),
  EXPIRED(4);

  companion object {
    fun ofRaw(raw: Int): NativeCheckoutStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Mirrors `CheckoutEvent` in the native cores. Lifecycle-only — never used
 * to decide the checkout outcome.
 */
enum class NativeEventType(val raw: Int) {
  OPENED(0),
  RETURN_RECEIVED(1),
  CLOSED(2);

  companion object {
    fun ofRaw(raw: Int): NativeEventType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class StartRequest (
  /** Absolute session URL from the merchant backend. */
  val checkoutUrl: String,
  /**
   * Absolute URL the native SDK watches for. Its scheme must be registered
   * as a URL type in Info.plist (iOS) / an intent-filter on the redirect
   * activity (Android), so the OS routes the checkout return back to this
   * app.
   */
  val returnUrl: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StartRequest {
      val checkoutUrl = pigeonVar_list[0] as String
      val returnUrl = pigeonVar_list[1] as String
      return StartRequest(checkoutUrl, returnUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      checkoutUrl,
      returnUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StartRequest
    return MessagesPigeonUtils.deepEquals(this.checkoutUrl, other.checkoutUrl) && MessagesPigeonUtils.deepEquals(this.returnUrl, other.returnUrl)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.checkoutUrl)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.returnUrl)
    return result
  }
  override fun toString(): String {
    return "StartRequest(checkoutUrl=$checkoutUrl, returnUrl=$returnUrl)"
  }
}

/**
 * Mirrors the native `CheckoutResult`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeCheckoutResult (
  val status: NativeCheckoutStatus,
  val paymentId: String? = null,
  val subscriptionId: String? = null,
  val licenseKeys: List<String>? = null,
  val customerEmail: String? = null,
  /** All query parameters from the return_url, verbatim. */
  val raw: Map<String, String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeCheckoutResult {
      val status = pigeonVar_list[0] as NativeCheckoutStatus
      val paymentId = pigeonVar_list[1] as String?
      val subscriptionId = pigeonVar_list[2] as String?
      val licenseKeys = pigeonVar_list[3] as List<String>?
      val customerEmail = pigeonVar_list[4] as String?
      val raw = pigeonVar_list[5] as Map<String, String>
      return NativeCheckoutResult(status, paymentId, subscriptionId, licenseKeys, customerEmail, raw)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      paymentId,
      subscriptionId,
      licenseKeys,
      customerEmail,
      raw,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeCheckoutResult
    return MessagesPigeonUtils.deepEquals(this.status, other.status) && MessagesPigeonUtils.deepEquals(this.paymentId, other.paymentId) && MessagesPigeonUtils.deepEquals(this.subscriptionId, other.subscriptionId) && MessagesPigeonUtils.deepEquals(this.licenseKeys, other.licenseKeys) && MessagesPigeonUtils.deepEquals(this.customerEmail, other.customerEmail) && MessagesPigeonUtils.deepEquals(this.raw, other.raw)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.status)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.paymentId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.subscriptionId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.licenseKeys)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.customerEmail)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.raw)
    return result
  }
  override fun toString(): String {
    return "NativeCheckoutResult(status=$status, paymentId=$paymentId, subscriptionId=$subscriptionId, licenseKeys=$licenseKeys, customerEmail=$customerEmail, raw=$raw)"
  }
}

/**
 * Mirrors the native `AbandonedSession`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NativeAbandonedSession (
  val sessionId: String,
  /** Milliseconds since the Unix epoch (UTC). */
  val createdAtMillis: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAbandonedSession {
      val sessionId = pigeonVar_list[0] as String
      val createdAtMillis = pigeonVar_list[1] as Long
      return NativeAbandonedSession(sessionId, createdAtMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sessionId,
      createdAtMillis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAbandonedSession
    return MessagesPigeonUtils.deepEquals(this.sessionId, other.sessionId) && MessagesPigeonUtils.deepEquals(this.createdAtMillis, other.createdAtMillis)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sessionId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.createdAtMillis)
    return result
  }
  override fun toString(): String {
    return "NativeAbandonedSession(sessionId=$sessionId, createdAtMillis=$createdAtMillis)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeCheckoutEvent (
  val type: NativeEventType
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeCheckoutEvent {
      val type = pigeonVar_list[0] as NativeEventType
      return NativeCheckoutEvent(type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeCheckoutEvent
    return MessagesPigeonUtils.deepEquals(this.type, other.type)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    return result
  }
  override fun toString(): String {
    return "NativeCheckoutEvent(type=$type)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeCheckoutStatus.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeEventType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StartRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeCheckoutResult.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAbandonedSession.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeCheckoutEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeCheckoutStatus -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is NativeEventType -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is StartRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NativeCheckoutResult -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is NativeAbandonedSession -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is NativeCheckoutEvent -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Implemented natively (Swift/Kotlin), called from Dart. Presents an
 * `SFSafariViewController` sheet on iOS, a Custom Tab on Android.
 *
 * Errors are surfaced as PlatformException with `code` set to one of the
 * shared native error codes: INVALID_CHECKOUT_URL, INVALID_RETURN_URL,
 * ALREADY_IN_PROGRESS, PLATFORM_ERROR.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface DodoCheckoutHostApi {
  /**
   * Presents the checkout and completes when it resolves. Lifecycle events
   * for this call are delivered via [DodoCheckoutFlutterApi.onCheckoutEvent]
   * for the call's duration.
   */
  fun start(request: StartRequest, callback: (Result<NativeCheckoutResult>) -> Unit)
  fun getAbandonedSession(): NativeAbandonedSession?
  fun clearAbandonedSession()
  /**
   * iOS only — forward incoming URLs here from your app's own URL-handling.
   * Required: `SFSafariViewController` has no in-process way to catch its
   * own return URL. No-op returning `false` on Android (Custom Tabs there is
   * fully self-contained via Activities). Returns `true` if the URL belonged
   * to an in-flight checkout.
   */
  fun handleOpenURL(url: String): Boolean

  companion object {
    /** The codec used by DodoCheckoutHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `DodoCheckoutHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DodoCheckoutHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as StartRequest
            api.start(requestArg) { result: Result<NativeCheckoutResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutHostApi.getAbandonedSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getAbandonedSession())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutHostApi.clearAbandonedSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearAbandonedSession()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutHostApi.handleOpenURL$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.handleOpenURL(urlArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Implemented in Dart, called from native. Delivers lifecycle events for
 * whichever checkout is currently in flight — logging/analytics only.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class DodoCheckoutFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by DodoCheckoutFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onCheckoutEvent(eventArg: NativeCheckoutEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.dodopayments_checkout.DodoCheckoutFlutterApi.onCheckoutEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
